Add feature preprocessing module
WayScience/mitocheck_data pull request #13
Opened 2022-06-28 20:31 UTC by roshankern

@gwaybio This should be ready for review. Not much done here right now, just pycytominer `normalization()` with default settings.

2022-06-28 20:39 UTC, gwaybio requested changes
Looks great! only a couple minor comments and requests.

2022-06-28 20:39 UTC, gwaybio commented on 4.preprocess_features/4.preprocess_features_env.yml
> +  - conda-forge::pycytominer=0.2.0
```suggestion
```

2022-06-28 20:39 UTC, gwaybio commented on 4.preprocess_features/4.preprocess_training_features.py
> +profile_dir = pathlib.Path("/home/roshankern/Desktop/Github/mitocheck_data/3.extract_features/outputs/efn_pretrained/features")
Can you use relative paths instead of absolute paths?

Relative paths will work for others, absolute paths will only work for people that use the exact same path as you (unlikely!)

2022-06-28 20:39 UTC, gwaybio commented on 4.preprocess_features/4.preprocess_training_features.py
> +deep_single_cell = DeepProfiler_processing.SingleCellDeepProfiler(deep_data)
can you add here two things:

1. a `print(deep_single_cell.shape)` call to determine the feature dimensions. how many single cells, how many features?
2. a `deep_single_cell.head()` call to determine what the data actually look like.

2022-06-28 20:39 UTC, gwaybio commented on 4.preprocess_features/4.preprocess_training_features.py
> +deep_single_cell = DeepProfiler_processing.SingleCellDeepProfiler(deep_data)
oh, but this is a class, not the actual data... hmm

2022-06-28 20:39 UTC, gwaybio commented on 4.preprocess_features/4.preprocess_training_features.py
> +deep_single_cell.normalize_deep_single_cells(output_file="normalized_training_data.csv")
Even though this uses all the default arguments, can you add them here? (only the pertinent ones, no need for the spherize-based args, only the ones that actually have an effect)

It is good to be explicit about what type of normalization happens, and someone who looks at this repo should understand immediately what method we performed.

2022-06-28 20:39 UTC, gwaybio commented on 4.preprocess_features/4.preprocess_training_features.py
> +
Can you read in the `normalized_training_data.csv` in a new cell and perform the print shape and .head() commands instead? It would be great to see the structure of the data 👀

2022-06-28 20:39 UTC, gwaybio commented on 4.preprocess_features/4.preprocess_training_features.py
> +deep_single_cell.normalize_deep_single_cells(output_file="normalized_training_data.csv")
typically, I like to put the data output in a separate folder (called `data/` or something similar).

It's much easier to navigate a repo as a new user if things are in expected places that are named well.

2022-06-28 20:39 UTC, gwaybio commented on 4.preprocess_features/README.md
> +## Step 2: Normalize Single Cell Training Features
Can you comment a bit on the nature of the normalization? What are you actually doing to the features?

2022-06-28 20:46 UTC, roshankern commented on 4.preprocess_features/4.preprocess_training_features.py
> +profile_dir = pathlib.Path("/home/roshankern/Desktop/Github/mitocheck_data/3.extract_features/outputs/efn_pretrained/features")
Ahhhh! Fixed in https://github.com/WayScience/mitocheck_data/pull/13/commits/a4c1ad07ada1e8bba3c05760b1d79f3e323371a8.

2022-06-28 21:23 UTC, roshankern commented on 4.preprocess_features/README.md
> +## Step 2: Normalize Single Cell Training Features
Let me know if my comments in https://github.com/WayScience/mitocheck_data/pull/13/commits/5d5837ba99fee0e33fd07cf64d15441e040d1393 suffice!

2022-06-28 21:23 UTC, roshankern commented on 4.preprocess_features/4.preprocess_training_features.py
> +
Done in https://github.com/WayScience/mitocheck_data/pull/13/commits/5d5837ba99fee0e33fd07cf64d15441e040d1393, except read normalized training data from `normalize_deep_single_cells()` instead of loading csv.

2022-06-28 21:25 UTC, roshankern commented on 4.preprocess_features/4.preprocess_training_features.py
> +deep_single_cell.normalize_deep_single_cells(output_file="normalized_training_data.csv")
Added the default arguments with some explanation in https://github.com/WayScience/mitocheck_data/pull/13/commits/5d5837ba99fee0e33fd07cf64d15441e040d1393.

As of https://github.com/WayScience/mitocheck_data/pull/13/commits/5d5837ba99fee0e33fd07cf64d15441e040d1393, the data output goes to `/data/`. Did you mean it should go inside `4.preprocess_features` (`4.preprocess_features/data/`)?

2022-06-28 21:27 UTC, gwaybio commented on 4.preprocess_features/4.preprocess_training_features.py
> +deep_single_cell.normalize_deep_single_cells(output_file="normalized_training_data.csv")
my sense is `4.preprocess_features/data/`, but I can be convinced otherwise!

If inside `data/` the filename might benefit from being more specific

2022-06-28 21:33 UTC, gwaybio commented on 4.preprocess_features/README.md
> +## Step 2: Normalize Single Cell Training Features
I think 0fb28e91ee15303e4c86032ea98919526e363a58 is the right commit. Details look good. Can you cite the LUAD paper? (and briefly motivate why we need to standardize)

2022-06-29 15:09 UTC, roshankern commented on 4.preprocess_features/4.preprocess_training_features.py
> +deep_single_cell.normalize_deep_single_cells(output_file="normalized_training_data.csv")
Moved to `4.preprocess_features/data/` in https://github.com/WayScience/mitocheck_data/pull/13/commits/6fe2cabd3570d71285c1015617ab782a06604ee2.

2022-06-29 15:12 UTC, roshankern commented on 4.preprocess_features/README.md
> +## Step 2: Normalize Single Cell Training Features
LUAD paper does not mention standardization, only negative control sphering.

2022-06-29 15:40 UTC, gwaybio approved these changes

2022-06-29 15:42 UTC, merged